import { pdf, Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import type { ResearchDoc } from "@/types/teardown";

const styles = StyleSheet.create({
  page: {
    padding: 48,
    backgroundColor: "#FDFAF6",
    fontFamily: "Helvetica",
  },
  coverPage: {
    padding: 48,
    backgroundColor: "#1C1412",
    fontFamily: "Helvetica",
    flex: 1,
    justifyContent: "center",
  },
  coverTitle: {
    fontSize: 32,
    fontFamily: "Helvetica-Bold",
    color: "#FFFFFF",
    marginBottom: 12,
  },
  coverSub: {
    fontSize: 14,
    color: "#A89890",
    marginBottom: 32,
  },
  coverAccent: {
    width: 48,
    height: 3,
    backgroundColor: "#C2451E",
    marginBottom: 16,
  },
  coverTag: {
    fontSize: 10,
    color: "#7C6E68",
  },
  sectionNum: {
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    color: "#C2451E",
    marginBottom: 4,
  },
  heading: {
    fontSize: 20,
    fontFamily: "Helvetica-Bold",
    color: "#1C1412",
    marginBottom: 8,
  },
  divider: {
    height: 1,
    backgroundColor: "#E8DDD2",
    marginBottom: 16,
  },
  body: {
    fontSize: 10,
    color: "#1C1412",
    lineHeight: 1.7,
    marginBottom: 16,
  },
  insightBox: {
    backgroundColor: "#FBF0EB",
    borderLeftWidth: 3,
    borderLeftColor: "#C2451E",
    padding: 10,
    marginTop: 8,
    marginBottom: 12,
  },
  insightText: {
    fontSize: 10,
    color: "#C2451E",
    fontFamily: "Helvetica-Oblique",
    lineHeight: 1.5,
  },
  statsRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 12,
  },
  statBox: {
    flex: 1,
    backgroundColor: "#F5EFE4",
    padding: 10,
    borderRadius: 4,
  },
  statValue: {
    fontSize: 16,
    fontFamily: "Helvetica-Bold",
    color: "#C2451E",
    marginBottom: 3,
  },
  statLabel: {
    fontSize: 8,
    color: "#1C1412",
  },
  statSub: {
    fontSize: 7,
    color: "#A89890",
    marginTop: 2,
  },
  pageFooter: {
    position: "absolute",
    bottom: 24,
    left: 48,
    right: 48,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  footerText: {
    fontSize: 8,
    color: "#D1C4BE",
  },
  sourceItem: {
    fontSize: 10,
    color: "#7C6E68",
    marginBottom: 6,
    lineHeight: 1.4,
  },
});

function ResearchPdfDoc({ productName, doc }: { productName: string; doc: ResearchDoc }) {
  return (
    <Document title={`${productName} — Product Teardown`} author="Tear">
      {/* Cover */}
      <Page size="A4" style={styles.coverPage}>
        <View style={styles.coverAccent} />
        <Text style={styles.coverTitle}>{productName}</Text>
        <Text style={styles.coverSub}>AI-Powered Product Teardown</Text>
        <Text style={styles.coverTag}>Generated by Tear</Text>
        <View style={styles.pageFooter}>
          <Text style={styles.footerText}>Tear · Product Teardown Platform</Text>
        </View>
      </Page>

      {/* One page per section */}
      {doc.sections.map((section, idx) => (
        <Page key={section.id} size="A4" style={styles.page}>
          <Text style={styles.sectionNum}>{String(idx + 1).padStart(2, "0")}</Text>
          <Text style={styles.heading}>{section.title}</Text>
          <View style={styles.divider} />
          <Text style={styles.body}>{section.content}</Text>
          {section.keyInsight && (
            <View style={styles.insightBox}>
              <Text style={styles.insightText}>→ {section.keyInsight}</Text>
            </View>
          )}
          {section.stats && section.stats.length > 0 && (
            <View style={styles.statsRow}>
              {section.stats.map((stat, i) => (
                <View key={i} style={styles.statBox}>
                  <Text style={styles.statValue}>{stat.value}</Text>
                  <Text style={styles.statLabel}>{stat.label}</Text>
                  {stat.sub && <Text style={styles.statSub}>{stat.sub}</Text>}
                </View>
              ))}
            </View>
          )}
          <View style={styles.pageFooter}>
            <Text style={styles.footerText}>Tear · {productName} Teardown</Text>
            <Text style={styles.footerText}>{idx + 1} / {doc.sections.length}</Text>
          </View>
        </Page>
      ))}

      {/* Sources */}
      <Page size="A4" style={styles.page}>
        <Text style={styles.heading}>Sources</Text>
        <View style={styles.divider} />
        {doc.sources.map((source) => (
          <Text key={source.num} style={styles.sourceItem}>
            [{source.num}] {source.title} — {source.domain}
          </Text>
        ))}
        <View style={styles.pageFooter}>
          <Text style={styles.footerText}>Tear · {productName} Teardown</Text>
        </View>
      </Page>
    </Document>
  );
}

export async function downloadResearchPdf(productName: string, doc: ResearchDoc) {
  const blob = await pdf(<ResearchPdfDoc productName={productName} doc={doc} />).toBlob();
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${productName.replace(/\s+/g, "-").toLowerCase()}-teardown.pdf`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
