import { NextRequest, NextResponse } from "next/server";
import PptxGenJS from "pptxgenjs";
import type { DeckData } from "@/types/teardown";

const BG      = "F5EFE4";
const PRIMARY = "C2451E";
const TEXT    = "1C1412";
const MUTED   = "7C6E68";
const ACCENT  = "FBF0EB";
const BORDER  = "E8DDD2";
const WHITE   = "FFFFFF";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function addHeader(s: any, pptx: PptxGenJS, sectionNum: string | undefined, title: string) {
  if (sectionNum) {
    s.addText(sectionNum, { x: 0.7, y: 0.45, w: 1.5, h: 0.35, fontSize: 10, bold: true, color: PRIMARY, fontFace: "Arial" });
  }
  s.addText(title, { x: 0.7, y: 0.82, w: 11.5, h: 0.62, fontSize: 22, bold: true, color: TEXT, fontFace: "Georgia" });
  s.addShape(pptx.ShapeType.rect, { x: 0.7, y: 1.5, w: 11.5, h: 0.03, fill: { color: BORDER } });
}

function addStats(
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  s: any,
  pptx: PptxGenJS,
  stats: Array<{ label: string; value: string; sub?: string }>,
  y: number,
) {
  const count = stats.length;
  const boxW  = Math.min(3.6, (11.5 - (count - 1) * 0.2) / count);
  stats.forEach((stat, i) => {
    const x = 0.7 + i * (boxW + 0.2);
    s.addShape(pptx.ShapeType.rect, { x, y, w: boxW, h: 1.35, fill: { color: WHITE }, line: { color: BORDER, width: 1.5 } });
    s.addText(stat.value, { x: x + 0.15, y: y + 0.12, w: boxW - 0.3, h: 0.52, fontSize: 18, bold: true, color: PRIMARY, fontFace: "Georgia" });
    s.addText(stat.label, { x: x + 0.15, y: y + 0.65, w: boxW - 0.3, h: 0.3, fontSize: 9, color: TEXT, fontFace: "Arial" });
    if (stat.sub) {
      s.addText(stat.sub, { x: x + 0.15, y: y + 0.95, w: boxW - 0.3, h: 0.28, fontSize: 8, color: MUTED, fontFace: "Arial" });
    }
  });
}

export async function POST(req: NextRequest) {
  const { productName, deckData } = (await req.json()) as {
    productName: string;
    deckData: DeckData;
  };

  const pptx = new PptxGenJS();
  pptx.layout = "LAYOUT_WIDE";

  for (const slide of deckData.slides) {
    const s = pptx.addSlide();
    s.background = { color: BG };

    switch (slide.type) {
      case "cover": {
        s.addShape(pptx.ShapeType.rect, { x: 0, y: 0, w: "100%", h: "100%", fill: { color: "1C1412" } });
        s.addShape(pptx.ShapeType.rect, { x: 0.7, y: 2.6, w: 0.6, h: 0.07, fill: { color: PRIMARY } });
        s.addText(slide.title, { x: 0.7, y: 2.8, w: 9, h: 1.1, fontSize: 36, bold: true, color: WHITE, fontFace: "Georgia" });
        s.addText(slide.subtitle ?? "", { x: 0.7, y: 4.0, w: 9, h: 0.5, fontSize: 15, color: "A89890", fontFace: "Arial" });
        s.addText("Generated by Tear", { x: 0.7, y: 6.6, w: 5, h: 0.35, fontSize: 9, color: "7C6E68", fontFace: "Arial" });
        break;
      }
      case "bullets": {
        addHeader(s, pptx, slide.sectionNum, slide.title);
        slide.bullets?.forEach((b, i) => {
          s.addText(
            [
              { text: b.text, options: { bold: true, fontSize: 12, color: TEXT } },
              ...(b.sub ? [{ text: "\n" + b.sub, options: { fontSize: 10, color: MUTED } }] : []),
            ],
            { x: 0.7, y: 1.65 + i * 0.88, w: 7.5, h: 0.78, fontFace: "Arial", valign: "middle" },
          );
        });
        if (slide.stats) addStats(s, pptx, slide.stats, 5.3);
        break;
      }
      case "features": {
        addHeader(s, pptx, slide.sectionNum, slide.title);
        slide.items?.forEach((item, i) => {
          const col = i % 3;
          const row = Math.floor(i / 3);
          s.addShape(pptx.ShapeType.rect, { x: 0.7 + col * 4.1, y: 1.65 + row * 1.55, w: 3.8, h: 1.35, fill: { color: WHITE }, line: { color: BORDER, width: 1 } });
          s.addText(item.name, { x: 0.9 + col * 4.1, y: 1.75 + row * 1.55, w: 3.4, h: 0.4, fontSize: 12, bold: true, color: PRIMARY, fontFace: "Arial" });
          s.addText(item.desc, { x: 0.9 + col * 4.1, y: 2.15 + row * 1.55, w: 3.4, h: 0.7, fontSize: 10, color: TEXT, fontFace: "Arial", wrap: true });
        });
        break;
      }
      case "pricing": {
        addHeader(s, pptx, slide.sectionNum, slide.title);
        slide.tiers?.forEach((tier, i) => {
          const x = 0.7 + i * 3.05;
          s.addShape(pptx.ShapeType.rect, { x, y: 1.6, w: 2.8, h: 2.2, fill: { color: tier.highlight ? PRIMARY : WHITE }, line: { color: tier.highlight ? PRIMARY : BORDER, width: 1.5 } });
          s.addText(tier.name, { x, y: 1.75, w: 2.8, h: 0.4, align: "center", fontSize: 12, bold: true, color: tier.highlight ? WHITE : TEXT, fontFace: "Arial" });
          s.addText(tier.price, { x, y: 2.25, w: 2.8, h: 0.55, align: "center", fontSize: 20, bold: true, color: tier.highlight ? WHITE : PRIMARY, fontFace: "Georgia" });
          s.addText(tier.target, { x, y: 2.88, w: 2.8, h: 0.35, align: "center", fontSize: 10, color: tier.highlight ? WHITE : MUTED, fontFace: "Arial" });
        });
        if (slide.revenueStats) addStats(s, pptx, slide.revenueStats, 4.6);
        break;
      }
      case "gtm": {
        addHeader(s, pptx, slide.sectionNum, slide.title);
        slide.phases?.forEach((phase, i) => {
          const x = 0.7 + i * 4.15;
          s.addShape(pptx.ShapeType.rect, { x, y: 1.6, w: 3.9, h: 3.0, fill: { color: WHITE }, line: { color: BORDER, width: 1.5 } });
          s.addText(String(i + 1).padStart(2, "0"), { x: x + 0.2, y: 1.75, w: 0.6, h: 0.4, fontSize: 10, bold: true, color: PRIMARY, fontFace: "Arial" });
          s.addText(phase.label, { x: x + 0.2, y: 2.2, w: 3.5, h: 0.45, fontSize: 13, bold: true, color: TEXT, fontFace: "Georgia" });
          s.addText(phase.desc, { x: x + 0.2, y: 2.75, w: 3.5, h: 1.0, fontSize: 10, color: TEXT, fontFace: "Arial", wrap: true });
          if (phase.metric) {
            s.addText(phase.metric, { x: x + 0.2, y: 4.1, w: 3.5, h: 0.35, fontSize: 11, bold: true, color: PRIMARY, fontFace: "Arial" });
          }
        });
        break;
      }
      case "techstack": {
        addHeader(s, pptx, slide.sectionNum, slide.title);
        slide.layers?.forEach((layer, i) => {
          s.addShape(pptx.ShapeType.rect, { x: 0.7, y: 1.6 + i * 0.82, w: 11.5, h: 0.72, fill: { color: i % 2 === 0 ? WHITE : ACCENT }, line: { color: BORDER, width: 1 } });
          s.addText(layer.layer, { x: 0.9, y: 1.65 + i * 0.82, w: 2.5, h: 0.62, fontSize: 11, bold: true, color: TEXT, fontFace: "Arial", valign: "middle" });
          s.addText(layer.detail, { x: 3.6, y: 1.65 + i * 0.82, w: 8.4, h: 0.62, fontSize: 11, color: MUTED, fontFace: "Arial", valign: "middle" });
        });
        break;
      }
      case "competitive": {
        addHeader(s, pptx, slide.sectionNum, slide.title);
        if (slide.tam) {
          s.addText(`TAM: ${slide.tam}  ·  CAGR: ${slide.cagr ?? ""}`, { x: 0.7, y: 1.45, w: 11, h: 0.32, fontSize: 11, color: MUTED, fontFace: "Arial" });
        }
        ["Competitor", "Angle", "Threat Level"].forEach((h, hi) => {
          s.addText(h, { x: 0.7 + hi * 4.0, y: 1.88, w: 3.7, h: 0.35, fontSize: 10, bold: true, color: TEXT, fontFace: "Arial" });
        });
        slide.competitors?.forEach((comp, i) => {
          const threatColor = comp.threat === "High" ? PRIMARY : comp.threat === "Medium" ? "D97706" : "6B7280";
          s.addShape(pptx.ShapeType.rect, { x: 0.7, y: 2.3 + i * 0.68, w: 11.5, h: 0.6, fill: { color: i % 2 === 0 ? WHITE : ACCENT }, line: { color: BORDER, width: 1 } });
          s.addText(comp.name, { x: 0.9, y: 2.34 + i * 0.68, w: 3.7, h: 0.52, fontSize: 11, color: TEXT, fontFace: "Arial", valign: "middle" });
          s.addText(comp.angle, { x: 4.7, y: 2.34 + i * 0.68, w: 3.7, h: 0.52, fontSize: 11, color: MUTED, fontFace: "Arial", valign: "middle" });
          s.addText(comp.threat, { x: 8.7, y: 2.34 + i * 0.68, w: 2.5, h: 0.52, fontSize: 11, bold: true, color: threatColor, fontFace: "Arial", valign: "middle" });
        });
        break;
      }
      case "stats": {
        addHeader(s, pptx, slide.sectionNum, slide.title);
        if (slide.stats) addStats(s, pptx, slide.stats, 1.65);
        if (slide.insight) {
          s.addShape(pptx.ShapeType.rect, { x: 0.7, y: 4.3, w: 11.5, h: 1.3, fill: { color: ACCENT }, line: { color: PRIMARY, width: 1.5 } });
          s.addText("→ " + slide.insight, { x: 0.9, y: 4.4, w: 11.1, h: 1.1, fontSize: 11, color: PRIMARY, fontFace: "Arial", italic: true, wrap: true, valign: "middle" });
        }
        break;
      }
      case "funding": {
        addHeader(s, pptx, slide.sectionNum, slide.title);
        ["Round", "Year", "Amount", "Lead Investor"].forEach((h, hi) => {
          s.addText(h, { x: 0.7 + hi * 2.9, y: 1.6, w: 2.7, h: 0.35, fontSize: 10, bold: true, color: TEXT, fontFace: "Arial" });
        });
        slide.rounds?.forEach((round, i) => {
          s.addShape(pptx.ShapeType.rect, { x: 0.7, y: 2.02 + i * 0.65, w: 11.5, h: 0.6, fill: { color: i % 2 === 0 ? WHITE : ACCENT }, line: { color: BORDER, width: 1 } });
          [round.round, round.year, round.amount, round.lead].forEach((val, vi) => {
            s.addText(val, { x: 0.9 + vi * 2.9, y: 2.05 + i * 0.65, w: 2.7, h: 0.54, fontSize: 10, color: TEXT, fontFace: "Arial", valign: "middle" });
          });
        });
        const summaryStats = [
          ...(slide.totalRaised ? [{ label: "Total Raised", value: slide.totalRaised }] : []),
          ...(slide.valuation   ? [{ label: "Valuation",    value: slide.valuation }]   : []),
          ...(slide.arr         ? [{ label: "Est. ARR",     value: slide.arr }]          : []),
        ];
        if (summaryStats.length) addStats(s, pptx, summaryStats, 5.05);
        break;
      }
      case "sources": {
        s.addText(slide.title, { x: 0.7, y: 0.8, w: 11.5, h: 0.75, fontSize: 24, bold: true, color: TEXT, fontFace: "Georgia" });
        s.addShape(pptx.ShapeType.rect, { x: 0.7, y: 1.6, w: 11.5, h: 0.03, fill: { color: BORDER } });
        slide.sources?.forEach((src, i) => {
          s.addText(src, { x: 0.7, y: 1.85 + i * 0.55, w: 11.5, h: 0.45, fontSize: 10, color: MUTED, fontFace: "Arial" });
        });
        break;
      }
    }

    // Footer on every slide
    s.addShape(pptx.ShapeType.rect, { x: 0, y: 7.35, w: 13.33, h: 0.15, fill: { color: PRIMARY } });
    s.addText(`Tear · ${productName} Teardown`, { x: 0.7, y: 7.0, w: 8, h: 0.3, fontSize: 8, color: "C4B5AE", fontFace: "Arial" });
  }

  const buffer = (await pptx.write({ outputType: "arraybuffer" })) as ArrayBuffer;
  const slug = productName.replace(/\s+/g, "-").toLowerCase();

  return new NextResponse(buffer, {
    headers: {
      "Content-Type": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
      "Content-Disposition": `attachment; filename="${slug}-teardown.pptx"`,
    },
  });
}
