"use client";

import { useEffect, useRef } from "react";
import { useSessionStore } from "@/store/session";
import type { ResearchSection } from "@/types/teardown";

function Cite({ num }: { num: number }) {
  return (
    <sup className="text-tear-primary text-[10px] font-mono cursor-pointer hover:underline ml-[1px]">
      [{num}]
    </sup>
  );
}

function SectionHeading({ num, title, id }: { num: string; title: string; id: string }) {
  return (
    <div id={id} className="flex items-baseline gap-3 pt-12 pb-3 border-b-[1.5px] border-tear-border mb-5 scroll-mt-6">
      <span className="font-mono text-[11px] text-tear-primary font-medium flex-shrink-0">{num}</span>
      <h2 className="font-lora text-[22px] font-semibold text-tear-text tracking-[-0.02em]">{title}</h2>
    </div>
  );
}

function InsightBox({ children }: { children: React.ReactNode }) {
  return (
    <div className="my-5 px-5 py-4 bg-[#FBF0EB] border-l-[3px] border-tear-primary rounded-r-[8px]">
      <span className="text-[10.5px] font-semibold tracking-[0.13em] uppercase text-tear-primary mb-2 block">
        Key Insight
      </span>
      <p className="text-[13.5px] leading-[1.7] text-[#3D2F2B] font-medium">{children}</p>
    </div>
  );
}

function DynamicTable({ label, headers, rows }: { label: string; headers: string[]; rows: string[][] }) {
  return (
    <div className="my-5 bg-[#F5EFE4] rounded-[10px] border border-tear-border overflow-hidden">
      <div className="px-5 py-3 border-b border-tear-border">
        <span className="text-[10.5px] font-semibold tracking-[0.13em] uppercase text-[#A89890]">{label}</span>
      </div>
      <div className="divide-y divide-[#EDE5DC]">
        {rows.map((row, ri) => (
          <div key={ri} className="grid px-5 py-3 gap-4" style={{ gridTemplateColumns: `repeat(${headers.length}, 1fr)` }}>
            {row.map((cell, ci) => (
              <span
                key={ci}
                className={`text-[13px] leading-[1.4] ${ci === 0 ? "font-semibold text-tear-text" : ci === 2 ? "font-medium text-tear-primary" : "text-tear-muted"}`}
              >
                {cell}
              </span>
            ))}
          </div>
        ))}
      </div>
    </div>
  );
}

function StatRow({ label, value, sub }: { label: string; value: string; sub?: string }) {
  return (
    <div className="flex items-start justify-between py-3 border-b border-tear-border last:border-0">
      <span className="text-[13px] text-tear-muted">{label}</span>
      <div className="text-right">
        <span className="text-[13px] font-semibold text-tear-text block">{value}</span>
        {sub && <span className="text-[11px] text-[#A89890]">{sub}</span>}
      </div>
    </div>
  );
}

function DynamicSection({ section, index }: { section: ResearchSection; index: number }) {
  const num = String(index + 1).padStart(2, "0");
  return (
    <div>
      <SectionHeading id={section.id} num={num} title={section.title} />
      {section.paragraphs?.map((para, i) => (
        <p key={i} className="text-[14.5px] leading-[1.8] text-tear-text mb-4">
          {para}
          {i === 0 && <Cite num={index + 1} />}
        </p>
      ))}
      {section.table && (
        <DynamicTable
          label={section.table.label}
          headers={section.table.headers}
          rows={section.table.rows}
        />
      )}
      {section.keyInsight && <InsightBox>{section.keyInsight}</InsightBox>}
      {section.stats?.map((s) => (
        <StatRow key={s.label} label={s.label} value={s.value} sub={s.sub} />
      ))}
    </div>
  );
}

interface DocumentBodyProps {
  productName: string;
  activeSection: string;
  onSectionChange: (id: string) => void;
}

export default function DocumentBody({ productName, activeSection }: DocumentBodyProps) {
  const researchDoc    = useSessionStore((s) => s.researchDoc);
  const isFirstRender  = useRef(true);

  useEffect(() => {
    if (isFirstRender.current) { isFirstRender.current = false; return; }
    const el = document.getElementById(activeSection);
    if (el) el.scrollIntoView({ behavior: "smooth", block: "start" });
  }, [activeSection]);

  if (!researchDoc) {
    return (
      <div className="flex-1 flex items-center justify-center">
        <span className="text-sm text-tear-muted animate-pulse">Document not found — run the pipeline first.</span>
      </div>
    );
  }

  return (
    <div className="flex-1 overflow-y-auto px-14 pb-24">
      {researchDoc.sections.map((section, i) => (
        <DynamicSection key={section.id} section={section} index={i} />
      ))}
      <p className="text-[12px] text-[#A89890] mt-8 pt-4 border-t border-tear-border">
        Research generated by Tear AI Pipeline · {productName} · {new Date().toLocaleDateString()}
      </p>
    </div>
  );
}
